// Code generated by "stringer -type=Provider"; DO NOT EDIT.

package provider

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Unknown-0]
	_ = x[BF2Hub-1]
	_ = x[PlayBF2-2]
	_ = x[OpenSpy-3]
	_ = x[B2BF2-4]
}

const _Provider_name = "UnknownBF2HubPlayBF2OpenSpyB2BF2"

var _Provider_index = [...]uint8{0, 7, 13, 20, 27, 32}

func (i Provider) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Provider_index)-1 {
		return "Provider(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Provider_name[_Provider_index[idx]:_Provider_index[idx+1]]
}
